name: CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  check:
    name: Verify the code
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.3.0
    - name: Set up JDK 8
      uses: actions/setup-java@v3.9.0
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Cache sbt
      uses: actions/cache@v3.2.6
      with:
        path: |
          ~/.sbt
          ~/.ivy2/cache
          ~/.coursier/cache/v1
          ~/.cache/coursier/v1
          ~/AppData/Local/Coursier/Cache/v1
          ~/Library/Caches/Coursier/v1
        key: ${{ runner.os }}-sbt-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}

    - run: |
        mkdir -p "$HOME/.ivy2"
        echo -e "realm=Dummy\nhost=example.com\nuser=user\npassword=password" > "$HOME/.ivy2/.credentials_nexus"

    - name: Verify the code
      run: sbt headerCheck scalafmtCheckAll

  build:
    name: Compile and test
    strategy:
      matrix:
        scala: [2.13.10]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.3.0
    - name: Set up JDK 8
      uses: actions/setup-java@v3.9.0
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Cache sbt
      uses: actions/cache@v3.2.6
      with:
        path: |
          ~/.sbt
          ~/.ivy2/cache
          ~/.coursier/cache/v1
          ~/.cache/coursier/v1
          ~/AppData/Local/Coursier/Cache/v1
          ~/Library/Caches/Coursier/v1
        key: ${{ runner.os }}-sbt-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}

    - run: |
        mkdir -p "$HOME/.ivy2"
        echo -e "realm=Dummy\nhost=example.com\nuser=user\npassword=password" > "$HOME/.ivy2/.credentials_nexus"

    - name: Run tests
      run: sbt ++${{ matrix.scala }} clean coverage test coverageReport

    - uses: codecov/codecov-action@v3.1.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
