name: Website
on:
  push:
    branches: [master]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.2.0
        with:
          fetch-depth: 0
      - uses: olafurpg/setup-scala@v13
      - uses: olafurpg/setup-gpg@v3
      - run: sbt 'docs/docusaurusPublishGhpages'
        env:
          GIT_DEPLOY_KEY: ${{ secrets.GIT_DEPLOY_KEY }}
